version: '3.9'

networks:
  topicos-network:
    name: topicos

services:
  player-database:
    image: postgres:11
    container_name: player-database
    volumes:
      - ./postgres-player:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - topicos-network
    ports:
      - "5435:5432"
    environment:
      - TZ=America/Fortaleza
      - POSTGRES_PASSWORD=player123
      - POSTGRES_USER=player
      - POSTGRES_DB=player
    restart: always

  canvas-database:
    image: postgres:11
    container_name: postgres-canva
    ports:
      - "5436:5432"
    volumes:
      - ./postgres-canvas:/var/lib/postgresql/data
    networks:
      - topicos-network
    environment:
      - TZ=America/Fortaleza
      - POSTGRES_PASSWORD=canva123
      - POSTGRES_USER=canva
      - POSTGRES_DB=canva
    restart: always

  redis:
    container_name: redis-topicos
    image: redis:6.2-alpine
    ports:
      - "7001:6379"
    networks:
      - topicos-network
    command: redis-server --requirepass redis123
    environment:
      - PASSWORD=redis123
    restart: always
    volumes:
      - ./redis_data:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "-p", "7000", "ping" ]
      interval: 10s
      timeout: 3s
      retries: 10
  rabbitmq:
    image: rabbitmq:3.12-management
    container_name: rabbitmq
    ports:
      - '5672:5672'
      - '15672:15672'
    volumes:
      - ./rabbitmq_data:/var/lib/rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=topicos
      - RABBITMQ_DEFAULT_PASS=topicos
    restart: always

  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - '2181:2181'
    environment:
      - ZOOKEEPER_CLIENT_PORT=2181
    restart: always

  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - '9092:9092'
    environment:
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_LISTENERS=PLAINTEXT://0.0.0.0:9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
    depends_on:
      - zookeeper
    restart: always


